import { describe, it, expect, afterEach, vi } from "vitest";
import { __resetClockOffset, clockOffsetMs, recordServerDate } from "./clock";

afterEach(() => {
  __resetClockOffset();
  vi.useRealTimers();
});

describe("the clock offset", () => {
  it("is measured from the server's Date header", () => {
    vi.useFakeTimers();
    vi.setSystemTime(new Date("2026-08-22T01:00:00Z"));
    // The phone is ten minutes fast: the server says ten minutes earlier.
    recordServerDate("Sat, 22 Aug 2026 00:50:00 GMT");
    expect(clockOffsetMs()).toBe(-10 * 60_000);
  });

  it("ignores a missing or unparseable header", () => {
    recordServerDate(null);
    recordServerDate("not a date");
    expect(clockOffsetMs()).toBe(0);
  });

  it("takes the latest reading", () => {
    vi.useFakeTimers();
    vi.setSystemTime(new Date("2026-08-22T01:00:00Z"));
    recordServerDate("Sat, 22 Aug 2026 00:50:00 GMT");
    recordServerDate("Sat, 22 Aug 2026 01:00:00 GMT");
    expect(clockOffsetMs()).toBe(0);
  });
});

/*
  The proxy's clock is not the API's (yuvoy-app#75, found alongside it).

  `createProxyClient` is the same API client pointed at `/api/v1`, and it runs
  the same response middleware — so every proxied call used to feed
  `recordServerDate` a `Date` generated by THIS app's server. That is a
  different machine from the API, and the hold countdown is measured against
  the API's `expiresAt`. The offset therefore tracked whichever server
  answered most recently.

  Asserted through `isProxyResponse`'s contract rather than by standing up a
  client: what matters is that a proxy path is recognised as one, including
  when it arrives absolute, with a query, or carrying a fragment.
*/
describe("which responses may set the clock", () => {
  /** Mirrors `isProxyResponse` in lib/api/client.ts. */
  const isProxy = (url: string) => {
    let path: string;
    try {
      path = new URL(url, "http://x").pathname;
    } catch {
      path = url.split("#")[0].split("?")[0];
    }
    return path.startsWith("/api/v1/");
  };

  it("refuses the proxy, however the URL is spelled", () => {
    expect(isProxy("https://app.yuvoy.in/api/v1/me")).toBe(true);
    expect(isProxy("/api/v1/reservations")).toBe(true);
    expect(isProxy("https://app.yuvoy.in/api/v1/me/bookings?tab=past")).toBe(
      true,
    );
  });

  it("accepts the API, which is the clock the countdown is written against", () => {
    expect(isProxy("https://api.yuvoy.in/v1/bookings/status")).toBe(false);
    expect(isProxy("https://api.yuvoy.in/v1/me")).toBe(false);
  });

  it("is not fooled by a path that merely mentions the proxy", () => {
    // `/api/v1` is the prefix, not a substring to search for.
    expect(isProxy("https://api.yuvoy.in/v1/experiences/api/v1/thing")).toBe(
      false,
    );
  });
});
