import Image from "next/image";
import { cn } from "@/lib/cn";

/**
 * The Yuvoy wordmark: the ensō with its terracotta dot and the tracked YUVOY
 * caps, side by side in one line. No tagline.
 *
 * ## Why there is only one drawing
 *
 * There were two. The delivered horizontal lockup bakes the handwritten
 * tagline and its tapered underline into the same file as the mark, so every
 * screen carrying the logo also carried a strapline over its content. The
 * owner asked on 14 Sep for it to go from every page, not only the reels feed
 * (yuvoy-app#36), and the `lockup` variant was deleted rather than left as a
 * prop somebody could pass again. A default is how a removed thing comes back.
 *
 * The remaining drawing is generated by `scripts/generate-feed-lockup.mjs`
 * from the delivered lockup, which lives in yuvoy-web (this repo no longer
 * keeps a copy). It drops the tagline and its underline and re-centres the
 * caps against the ensō. It is never hand-edited: a hand-edit is invisible in
 * review and is silently lost the next time the brand redelivers.
 *
 * Two tone variants, because a cream ensō is invisible on cream and a forest
 * one is invisible on forest. That is the §1 tone pairing, and it is why there
 * are two files rather than one recoloured at runtime.
 *
 * `unoptimized`: an SVG needs no optimiser pass, and this keeps
 * `dangerouslyAllowSVG` out of the image config.
 *
 * Size it from outside with a height class, and the height means the DRAWING's
 * height: the generated files crop the delivered canvas's empty margins, so
 * `h-7` is 28px of art. The art's ~4:1 ratio sets the width from there.
 */

/*
  The cropped art box the generator emits, not the delivered 1600x500 canvas,
  a third of whose height is empty margin.
*/
const ART = { width: 1007, height: 253 } as const;

/** Keyed by the colour of the MARK, not of the surface. */
const SRC = {
  cream: "/brand/yuvoy-mark-compact-on-dark.svg",
  forest: "/brand/yuvoy-mark-compact-on-light.svg",
} as const;

export function Wordmark({
  tone = "cream",
  className,
  priority = false,
}: {
  /** The colour of the MARK, chosen to contrast with the surface behind it. */
  tone?: "cream" | "forest";
  className?: string;
  priority?: boolean;
}) {
  return (
    <Image
      src={SRC[tone]}
      alt="Yuvoy"
      width={ART.width}
      height={ART.height}
      unoptimized
      priority={priority}
      className={cn("h-7 w-auto", className)}
    />
  );
}

/**
 * The ensō alone, without the wordmark.
 *
 * For places too tight for the lockup — an empty state, a loading mark. Same
 * two-file reasoning as above.
 */
export function Mark({
  tone = "cream",
  className,
}: {
  tone?: "cream" | "forest";
  className?: string;
}) {
  return (
    <Image
      src={`/brand/yuvoy-mark-vector-${tone}.svg`}
      alt=""
      aria-hidden="true"
      width={512}
      height={512}
      unoptimized
      className={cn("size-8", className)}
    />
  );
}
