import Image from "next/image";
import { cn } from "@/lib/cn";

/**
 * The Yuvoy wordmark — the owner-delivered horizontal lockup.
 *
 * The ensō with its terracotta dot, the tracked YUVOY caps, the handwritten
 * "Experience more." and its tapered underline, all one drawing. This is the
 * real mark, ported from yuvoy-web; the earlier typographic stand-in is gone.
 *
 * Two surface variants, generated by yuvoy-web's scripts and never hand-edited:
 * the cream/terra-soft drawing for dark surfaces, and a forest/terra-deep
 * recolour for cream ones — the §1 tone pairings. A cream ensō is invisible on
 * cream and a forest one is invisible on forest, which is why there are two
 * files rather than one recoloured at runtime.
 *
 * `unoptimized`: an SVG needs no optimiser pass, and this keeps
 * `dangerouslyAllowSVG` out of the image config.
 *
 * Size it from outside with a height class. The generated variants crop the
 * delivered canvas's empty margins, so the height means the DRAWING's height.
 */
export function Wordmark({
  tone = "cream",
  className,
  priority = false,
}: {
  /** The colour of the MARK, chosen to contrast with the surface behind it. */
  tone?: "cream" | "forest";
  className?: string;
  priority?: boolean;
}) {
  return (
    <Image
      src={`/brand/yuvoy-lockup-vector-${tone}.svg`}
      alt="Yuvoy"
      width={865}
      height={759}
      unoptimized
      priority={priority}
      className={cn("h-8 w-auto", className)}
    />
  );
}

/**
 * The ensō alone, without the wordmark.
 *
 * For places too tight for the lockup — an empty state, a loading mark. Same
 * two-file reasoning as above.
 */
export function Mark({
  tone = "cream",
  className,
}: {
  tone?: "cream" | "forest";
  className?: string;
}) {
  return (
    <Image
      src={`/brand/yuvoy-mark-vector-${tone}.svg`}
      alt=""
      aria-hidden="true"
      width={512}
      height={512}
      unoptimized
      className={cn("size-8", className)}
    />
  );
}
