import Image from "next/image";
import { cn } from "@/lib/cn";

/**
 * The Yuvoy wordmark — the owner-delivered HORIZONTAL header lockup, the same
 * drawing and the same two files the marketing site's header carries.
 *
 * The ensō with its terracotta dot, the tracked YUVOY caps, the handwritten
 * "Experience more." and its tapered underline, side by side in one line. It
 * replaces the stacked near-square lockup this app used to draw: the two
 * products wore different marks, and inside a 56px chrome strip the stacked
 * one had to shrink until its tagline was noise. One lockup, both products.
 *
 * Two surface variants, generated by yuvoy-web's scripts/generate-header-lockup.mjs
 * and never hand-edited: the delivered cream/terra-soft drawing for forest
 * surfaces, and a forest/terra-deep recolour for cream ones — the §1 tone
 * pairings. A cream ensō is invisible on cream and a forest one is invisible
 * on forest, which is why there are two files rather than one recoloured at
 * runtime.
 *
 * `unoptimized`: an SVG needs no optimiser pass, and this keeps
 * `dangerouslyAllowSVG` out of the image config.
 *
 * Size it from outside with a height class, and the height means the DRAWING's
 * height: the generated variants crop the delivered canvas's empty margins, so
 * `h-9` is 36px of art. The art's ~3.6:1 ratio sets the width from there.
 */

/*
  The cropped art boxes the generators emit — not the delivered 1600x500
  canvas, a third of whose height is empty margin.

  `lockup` is the full horizontal mark (1247x347, ~3.6:1).

  `compact` is the ensō and the YUVOY caps with the tagline removed and the
  caps re-centred against the mark (~4:1), from
  `scripts/generate-feed-lockup.mjs`. It exists for the reels feed: the tagline
  is baked into the delivered file, and a reel is the one surface where the
  product is the picture and the chrome has to get out of its way
  (yuvoy-app#36). Both are generated and neither is hand-edited.
*/
const ART = {
  lockup: { width: 1247, height: 347 },
  compact: { width: 1007, height: 253 },
} as const;

/** Keyed by the variant, then by the colour of the MARK, not of the surface. */
const SRC = {
  lockup: {
    cream: "/brand/yuvoy-lockup-on-dark.svg",
    forest: "/brand/yuvoy-lockup-on-light.svg",
  },
  compact: {
    cream: "/brand/yuvoy-mark-compact-on-dark.svg",
    forest: "/brand/yuvoy-mark-compact-on-light.svg",
  },
} as const;

export function Wordmark({
  tone = "cream",
  variant = "lockup",
  className,
  priority = false,
}: {
  /** The colour of the MARK, chosen to contrast with the surface behind it. */
  tone?: "cream" | "forest";
  /** `compact` drops the "Experience more." tagline. See `ART`. */
  variant?: "lockup" | "compact";
  className?: string;
  priority?: boolean;
}) {
  return (
    <Image
      src={SRC[variant][tone]}
      alt="Yuvoy"
      width={ART[variant].width}
      height={ART[variant].height}
      unoptimized
      priority={priority}
      className={cn("h-9 w-auto", className)}
    />
  );
}

/**
 * The ensō alone, without the wordmark.
 *
 * For places too tight for the lockup — an empty state, a loading mark. Same
 * two-file reasoning as above.
 */
export function Mark({
  tone = "cream",
  className,
}: {
  tone?: "cream" | "forest";
  className?: string;
}) {
  return (
    <Image
      src={`/brand/yuvoy-mark-vector-${tone}.svg`}
      alt=""
      aria-hidden="true"
      width={512}
      height={512}
      unoptimized
      className={cn("size-8", className)}
    />
  );
}
